---
sidebar: sidebar 
permalink: concept_nw_concepts_chars.html 
keywords: ontap select, networking concepts, cluster characteristics 
summary: 'Per prima cosa, è opportuno acquisire familiarità con i concetti generali di rete applicabili all"ambiente ONTAP Select . Successivamente, è opportuno esplorare le caratteristiche e le opzioni specifiche disponibili con i cluster a nodo singolo e multi-nodo.' 
---
= ONTAP Select concetti e caratteristiche di rete
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Per prima cosa, è opportuno acquisire familiarità con i concetti generali di rete applicabili all'ambiente ONTAP Select . Successivamente, è opportuno esplorare le caratteristiche e le opzioni specifiche disponibili con i cluster a nodo singolo e multi-nodo.



== Rete fisica

La rete fisica supporta l'implementazione di un cluster ONTAP Select principalmente fornendo l'infrastruttura di switching di livello due sottostante. La configurazione relativa alla rete fisica include sia l'host hypervisor sia l'ambiente di rete commutato più ampio.



=== Opzioni NIC host

Ogni host hypervisor ONTAP Select deve essere configurato con due o quattro porte fisiche. La configurazione esatta scelta dipende da diversi fattori, tra cui:

* Se il cluster contiene uno o più host ONTAP Select
* Quale sistema operativo hypervisor viene utilizzato
* Come è configurato lo switch virtuale
* Se LACP viene utilizzato con i collegamenti o meno




=== Configurazione dello switch fisico

È necessario assicurarsi che la configurazione degli switch fisici supporti l'implementazione di ONTAP Select . Gli switch fisici sono integrati con gli switch virtuali basati su hypervisor. La configurazione esatta scelta dipende da diversi fattori. Le considerazioni principali includono quanto segue:

* Come manterrete la separazione tra le reti interne ed esterne?
* Manterrete una separazione tra le reti dati e quelle di gestione?
* Come verranno configurate le VLAN di livello due?




== Reti logiche

ONTAP Select utilizza due diverse reti logiche, separando il traffico in base alla tipologia. Nello specifico, il traffico può fluire tra gli host all'interno del cluster, nonché verso i client di storage e altre macchine esterne al cluster. Gli switch virtuali gestiti dagli hypervisor contribuiscono a supportare la rete logica.



=== Rete interna

Con un'implementazione cluster multi-nodo, i singoli nodi ONTAP Select comunicano tramite una rete "interna" isolata. Questa rete non è esposta o disponibile al di fuori dei nodi del cluster ONTAP Select .


NOTE: La rete interna è presente solo con un cluster multi-nodo.

La rete interna ha le seguenti caratteristiche:

* Utilizzato per elaborare il traffico intra-cluster ONTAP , tra cui:
+
** Grappolo
** Interconnessione ad alta disponibilità (HA-IC)
** Specchio di sincronizzazione RAID (RSM)


* Rete a singolo strato-due basata su una VLAN
* Gli indirizzi IP statici vengono assegnati da ONTAP Select:
+
** Solo IPv4
** DHCP non utilizzato
** Indirizzo link-local


* La dimensione MTU è di 9000 byte per impostazione predefinita e può essere regolata nell'intervallo 7500-9000 (inclusi)




=== Rete esterna

La rete esterna elabora il traffico tra i nodi di un cluster ONTAP Select e i client di storage esterni, nonché le altre macchine. La rete esterna è parte integrante di ogni distribuzione cluster e presenta le seguenti caratteristiche:

* Utilizzato per elaborare il traffico ONTAP , tra cui:
+
** Dati (NFS, CIFS, iSCSI)
** Gestione (cluster e nodo; facoltativamente SVM)
** Intercluster (facoltativo)


* Supporta facoltativamente le VLAN:
+
** Gruppo di porte dati
** Gruppo di porte di gestione


* Indirizzi IP assegnati in base alle scelte di configurazione dell'amministratore:
+
** IPv4 o IPv6


* La dimensione MTU è di 1500 byte per impostazione predefinita (può essere modificata)


La rete esterna è presente con cluster di tutte le dimensioni.



== Ambiente di rete della macchina virtuale

L'host dell'hypervisor fornisce numerose funzionalità di rete.

ONTAP Select si basa sulle seguenti funzionalità esposte tramite la macchina virtuale:

Porte della macchina virtuale:: ONTAP Select dispone di diverse porte utilizzabili. L'assegnazione e l'utilizzo di queste porte dipendono da diversi fattori, tra cui la dimensione del cluster.
Interruttore virtuale:: Il software dello switch virtuale all'interno dell'ambiente hypervisor, sia esso vSwitch (VMware) o Open vSwitch (KVM), collega le porte esposte dalla macchina virtuale alle porte NIC Ethernet fisiche. È necessario configurare un vSwitch per ogni host ONTAP Select , in base alle esigenze del proprio ambiente.

