---
sidebar: sidebar 
permalink: concept_api_how_access.html 
keywords: rest api, deploy rest api, rest, access, accessing, how to access 
summary: 'Grazie alla flessibilità intrinseca dei servizi Web REST, è possibile accedere all"API ONTAP Select Deploy in diversi modi.' 
---
= Come accedere all'API ONTAP Select Deploy
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Grazie alla flessibilità intrinseca dei servizi Web REST, è possibile accedere all'API ONTAP Select Deploy in diversi modi.


NOTE: All'API REST inclusa in ONTAP Select Deploy viene assegnato un numero di versione. Il numero di versione dell'API è indipendente dal numero di release di Deploy. L'utilità di amministrazione ONTAP Select 9.17.1 Deploy include la versione 3 dell'API REST.



== Distribuisci l'interfaccia utente nativa dell'utilità

Il modo principale per accedere all'API è tramite l'interfaccia utente web ONTAP Select Deploy. Il browser effettua chiamate all'API e riformatta i dati in base al design dell'interfaccia utente. È possibile accedere all'API anche tramite l'interfaccia a riga di comando dell'utility Deploy.



== Pagina della documentazione online ONTAP Select Deploy

La pagina della documentazione online ONTAP Select Deploy fornisce un punto di accesso alternativo quando si utilizza un browser. Oltre a fornire un modo per eseguire direttamente singole chiamate API, la pagina include anche una descrizione dettagliata dell'API, inclusi i parametri di input e altre opzioni per ciascuna chiamata. Le chiamate API sono organizzate in diverse aree funzionali o categorie.



== Programma personalizzato

È possibile accedere all'API Deploy utilizzando diversi linguaggi di programmazione e strumenti. Tra i più diffusi ci sono Python, Java e cURL. Un programma, uno script o uno strumento che utilizza l'API funge da client di servizi web REST. L'utilizzo di un linguaggio di programmazione consente di comprendere meglio l'API e offre l'opportunità di automatizzare le distribuzioni ONTAP Select .
