---
sidebar: sidebar 
permalink: concept_ots_deploy.html 
keywords: ontap select deploy, deploy administration utility, deploy utility, functionality, accessing 
summary: 'ONTAP Select Deploy è l"utility di amministrazione utilizzata per distribuire e gestire i cluster ONTAP Select .' 
---
= ONTAP Select Distribuisci
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select Deploy è l'utility di amministrazione utilizzata per distribuire e gestire i cluster ONTAP Select . Deploy è fornito come una macchina virtuale Linux che è necessario installare prima di creare un cluster ONTAP Select .



== Funzionalità di base

L'utilità di amministrazione Deploy esegue le seguenti funzioni principali:

* Registrare i dettagli di ciascun host hypervisor in cui è distribuito ONTAP Select
* Configurare gli host e installare le licenze richieste
* Distribuisci e gestisci i cluster ONTAP Select
* Mantenere un inventario dei cluster e degli host ONTAP Select
* Raccogli e invia i dati AutoSupport a NetApp
* Mantenere un set interno di immagini dei nodi ONTAP Select
* Supporta i formati e i protocolli dei comandi specifici dell'hypervisor




== Modi per accedere all'utilità Deploy

Sono disponibili diverse opzioni per accedere all'utilità di amministrazione Deploy. Tutte le interfacce esterne sono funzionalmente equivalenti. È consigliabile selezionare l'opzione di accesso più adatta ai propri obiettivi e requisiti di distribuzione specifici. In tutti i casi, è necessario accedere utilizzando l'account amministratore con una password valida.



=== Interfaccia utente grafica web

È possibile accedere all'utilità Deploy tramite un browser web moderno. L'interfaccia utente grafica (UI) web offre un'interfaccia intuitiva e facile da usare e, nella maggior parte dei casi, costituirà l'interfaccia principale durante l'utilizzo dell'utilità.



=== Interfaccia della riga di comando

Un'interfaccia a riga di comando basata su testo è disponibile tramite la shell di gestione. È possibile accedere alla shell di gestione CLI nei seguenti modi:

* Shell sicura (SSH)
* Console della macchina virtuale


In genere, la console della macchina virtuale viene utilizzata come parte del processo di installazione e configurazione iniziale. Tuttavia, nella maggior parte dei casi, SSH offre un'opzione più flessibile e pratica.



=== API dei servizi web REST

L'API dei servizi web REST esposta ai client esterni offre un'ulteriore opzione per la connessione all'utilità Deploy. È possibile accedere all'API utilizzando qualsiasi linguaggio di programmazione o strumento tradizionale che supporti i servizi web REST. Tra le opzioni più comuni figurano:

* Pitone
* Giava
* Arricciare


L'utilizzo di un linguaggio di programmazione o di scripting offre l'opportunità di automatizzare la distribuzione e la gestione dei cluster ONTAP Select .



=== Pagina web della documentazione online ONTAP Select

Visualizzare la pagina web della documentazione online nell'utility Deploy è un modo alternativo per accedere all'API dei servizi web REST. Tuttavia, anziché utilizzare un linguaggio di programmazione, è possibile accedere all'API di gestione tramite la pagina web utilizzando un browser. Sono disponibili le seguenti funzionalità:

* Una descrizione dettagliata di ogni chiamata nell'API dei servizi Web REST
* La possibilità di emettere manualmente una qualsiasi delle chiamate API


È possibile accedere alla pagina della documentazione online utilizzando l'IP o il nome di dominio della macchina virtuale Deploy. Per visualizzare la pagina, inserisci un URL con il seguente formato nel tuo browser (sostituendo l'indirizzo IP o il nome di dominio appropriato per la tua istanza Deploy VM): `\http://<ip_address>/api/ui`
