---
sidebar: sidebar 
permalink: concept_lic_cp_operation.html 
keywords: license, licensing, Capacity Pools, operation details 
summary: Il modello di licenza Capacity Pools è diverso dal modello Capacity Tiers. Invece di dedicare la capacità di storage a ciascun singolo nodo, la capacità di storage viene allocata a un pool e condivisa tra più nodi. Sono stati creati componenti e processi aggiuntivi per supportare il modello Capacity Pools. 
---
= Dettagli operativi per il modello di licenza ONTAP Select Capacity Pools
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Il modello di licenza Capacity Pools è diverso dal modello Capacity Tiers. Invece di dedicare la capacità di storage a ciascun singolo nodo, la capacità di storage viene allocata a un pool e condivisa tra più nodi. Sono stati creati componenti e processi aggiuntivi per supportare il modello Capacity Pools.



== Gestore delle licenze

License Manager viene eseguito come processo separato all'interno di ogni istanza dell'utilità di amministrazione Deploy. Alcune delle funzioni fornite da LM includono:

* Generare un numero di serie univoco di venti cifre per ciascun nodo in base al numero di serie della licenza Capacity Pool
* Crea contratti di locazione per la capacità dai pool di capacità condivisi in base alle richieste dei nodi ONTAP Select
* Segnala le informazioni sull'utilizzo del pool tramite l'interfaccia utente Deploy




== Caratteristiche del contratto di locazione

Lo spazio di archiviazione allocato per ogni aggregato di dati su un nodo che utilizza una licenza Capacity Pool deve avere un lease associato. Il nodo richiede un lease di spazio di archiviazione e, se la capacità è disponibile, License Manager risponde con un lease. Ogni lease ha i seguenti attributi espliciti o impliciti:

* License Manager Ogni nodo ONTAP Select è associato a un'istanza di License Manager
* Pool di capacità Ogni nodo ONTAP Select è associato a un pool di capacità
* Assegnazione dello spazio di archiviazione Nel contratto di locazione viene assegnato un valore di capacità specifico
* Data e ora di scadenza I contratti di locazione hanno una durata compresa tra un'ora e sette giorni, a seconda della configurazione dell'utente.




== ID blocco licenza

Ogni istanza di License Manager, e quindi ogni istanza dell'utility Deploy corrispondente, è identificata da un numero univoco a 128 bit. Questo numero viene combinato con il numero di serie della licenza Capacity Pool a nove cifre per bloccare il pool a una specifica istanza di License Manager (che è di fatto un'istanza di Deploy). È necessario fornire entrambi i valori sul sito di supporto NetApp durante la generazione del file di licenza NetApp (NLF).

È possibile determinare l'ID di blocco della licenza per l'istanza di Deploy tramite l'interfaccia utente Web nei seguenti modi:

* Pagina introduttiva Questa pagina viene visualizzata al primo accesso a Deploy. È anche possibile visualizzare la pagina facendo clic sul menu a discesa in alto a destra della pagina e selezionando "Introduzione". Il LLID viene visualizzato nella sezione "Aggiungi licenze".
* Amministrazione Fare clic sulla scheda *Amministrazione* nella parte superiore della pagina, quindi fare clic su *Sistemi* e *Impostazioni*.




== Operazioni di leasing di base

Un nodo ONTAP Select deve individuare o richiedere un lease di capacità valido ogni volta che un aggregato di dati viene creato, espanso o modificato. È possibile utilizzare un lease ottenuto da una richiesta precedente ancora valido oppure, se necessario, richiederne uno nuovo. Il nodo ONTAP Select esegue i seguenti passaggi per individuare un lease di Capacity Pool:

. Se nel nodo è presente un contratto di locazione esistente, questo viene utilizzato a condizione che siano soddisfatte tutte le seguenti condizioni:
+
** Il contratto di locazione non è scaduto
** La richiesta di stoccaggio per l'aggregato non supera la capacità di locazione


. Se non è possibile individuare un lease esistente, il nodo richiede un nuovo lease al License Manager.




== Restituire la capacità di archiviazione a un pool di capacità

La capacità di storage viene allocata da un Capacity Pool in base alle esigenze e ogni nuova richiesta può ridurre lo spazio di storage disponibile nel pool. La capacità di storage viene restituita al pool in diverse situazioni, tra cui:

* Il contratto di locazione per un aggregato di dati scade e non viene rinnovato dal nodo
* L'aggregato di dati è stato eliminato



NOTE: Se una macchina virtuale ONTAP Select viene eliminata, tutti i lease attivi rimangono validi fino alla loro scadenza. Quando ciò accade, la capacità viene restituita al pool.
