---
sidebar: sidebar 
permalink: concept_lic_evaluation.html 
keywords: license, licensing, evaluation, upgrade license 
summary: 'È possibile utilizzare una licenza di valutazione se si desidera valutare ONTAP Select prima di decidere di acquistarlo. La licenza di valutazione è inclusa nell"utility di amministrazione ONTAP Select Deploy e viene applicata automaticamente a ciascun nodo ONTAP Select come parte di una distribuzione di valutazione.' 
---
= Licenze di valutazione per le distribuzioni ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile distribuire ONTAP Select con una licenza di valutazione o una licenza acquistata. La licenza scelta deve essere applicata a ciascuno dei nodi del cluster ONTAP Select e, di conseguenza, all'intero cluster. È possibile utilizzare una licenza di valutazione se si desidera valutare ONTAP Select prima di decidere di acquistarlo. La licenza di valutazione è inclusa nell'utility di amministrazione ONTAP Select Deploy e viene applicata automaticamente a ciascun nodo ONTAP Select come parte di una distribuzione di valutazione.

[NOTE]
====
Per scaricare l'utilità di amministrazione ONTAP Select Deploy, è necessario quanto segue:

* Un account registrato sul sito di supporto NetApp . Se non hai un account, vedi https://mysupport.netapp.com/site/user/registration["Registrazione utente"^] .
* A https://mysupport.netapp.com/site/downloads/evaluation/ontap-select["accettare il contratto di licenza per l'utente finale"^] per una distribuzione ONTAP Select con una licenza di valutazione.


====
Quando si distribuisce e si supporta un cluster di valutazione, è necessario tenere in considerazione diverse considerazioni:

* È possibile utilizzare il cluster solo a scopo di valutazione. Non è consentito utilizzare un cluster con licenza di valutazione in un ambiente di produzione.
* Quando si configura ciascun host, è necessario utilizzare l'utilità di amministrazione ONTAP Select Deploy come segue:
+
** Non fornire un numero di serie
** Configurare per utilizzare una licenza di valutazione






== Caratteristiche della licenza

La licenza di valutazione ONTAP Select presenta le seguenti caratteristiche:

* Non è richiesta una licenza di produzione con capacità di archiviazione
* Il numero di serie del nodo è composto da venti cifre e viene generato automaticamente da ONTAP Select Deploy
+
(non lo si acquista direttamente da NetApp)

* Il periodo di valutazione previsto dalla licenza può arrivare fino a 90 giorni
* Lo spazio di archiviazione massimo assegnato da ciascun nodo è lo stesso di una licenza di produzione




== Passa a una licenza di produzione

È possibile aggiornare un cluster di valutazione ONTAP Select per utilizzare una licenza di produzione. È necessario tenere presente le seguenti restrizioni:

* È necessario utilizzare l'utilità di amministrazione Deploy per eseguire l'aggiornamento della licenza
* È possibile utilizzare una licenza Capacity Tier, tuttavia la licenza Capacity Pools non è supportata
* Ogni nodo deve avere abbastanza spazio di archiviazione allocato per supportare il minimo richiesto per una licenza di produzione, in base alle dimensioni del cluster


Vederelink:task_adm_licenses.html["Convertire una licenza di valutazione in una licenza di produzione"] per maggiori informazioni.

.Informazioni correlate
* link:concept_lic_production.html["Scopri di più sulle licenze per le distribuzioni di produzione"]
* link:deploy-evaluation-ontap-select-ovf-template.html["Distribuisci un'istanza di valutazione di 90 giorni di un cluster ONTAP Select"]

