---
sidebar: sidebar 
permalink: reference_new_ots.html 
keywords: new features 
// summary: The current release includes several new features and improvements specific to ONTAP Select. 
summary: La versione corrente include diverse nuove funzionalità o miglioramenti specifici di ONTAP Select. 
---
= Novità per ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Scopri le nuove funzionalità e i miglioramenti nelle versioni supportate di ONTAP Select.



== ONTAP Select 9.17.1

ONTAP Select 9.17.1 include numerose nuove funzionalità e miglioramenti.

Supporto RAID software per dischi NVMe collegati localmente su host KVM:: ONTAP Select 9.17.1 introduce il supporto RAID software per i dischi NVMe ONTAP Select collegati localmente su un host hypervisor KVM (Kernel-Based Virtual Machine).
+
--
Per utilizzare il RAID software per i dischi NVMe collegati localmente, è necessariolink:kvm-host-configuration-and-preparation-checklist.html["configurare il passthrough PCI (DirectPath IO)"] quando si prepara l'host KVM. Ciò fornisce all'host KVM l'accesso diretto ai dischi NVMe collegati localmente, necessario per le seguenti attività:

* Configurazione dell'host KVM per l'utilizzo di unità NVMe
* Utilizzo del software RAID dopo aver distribuito il cluster


link:concept_stor_swraid_local.html["Scopri di più sui servizi di configurazione RAID software per l'archiviazione locale collegata"].

--
Supporto per l'espansione e la contrazione del cluster sugli host KVM:: A partire da ONTAP Select 9.17.1, la funzionalità di espansione e contrazione dei cluster è supportata sia per gli host KVM (Kernel-Based Virtual Machine) che per gli host hypervisor ESXi. Per ONTAP Select 9.16.1 e 9.15.1, l'espansione e la contrazione dei cluster sono supportate solo per gli host hypervisor ESXi.
+
--
È possibile utilizzare la funzionalità di espansione e contrazione del cluster su un cluster ONTAP Select esistente per aumentare le dimensioni da un cluster a sei nodi a uno a otto nodi o per ridurle da un cluster a otto nodi a uno a sei nodi.

link:task_cluster_expansion_contraction.html["Scopri di più sull'espansione e la contrazione del cluster e sulle versioni supportate degli hypervisor KVM ed ESXi"].

--
Supporto migliorato per l'espansione e la contrazione del cluster sugli host ESXi:: A partire da ONTAP Select 9.17.1, l'espansione e la contrazione del cluster sono supportate per cluster da sei a dodici nodi su host ESXi:
+
--
--
È possibile aumentare le dimensioni del cluster per un cluster ESXi esistente nei seguenti incrementi:

* Da sei nodi a otto, dieci o dodici nodi
* Da otto nodi a dieci o dodici nodi
* Da dieci a dodici nodi


È possibile ridurre le dimensioni del cluster per un cluster ESXi esistente nei seguenti incrementi:

* Da dodici nodi a dieci, otto o sei nodi
* Da dieci nodi a otto o sei nodi
* Da otto a sei nodi


--
link:task_cluster_expansion_contraction.html["Scopri di più sull'espansione e la contrazione del cluster e sulle versioni supportate degli hypervisor KVM ed ESXi"].

--
Supporto per il cloud SnapMirror:: A partire da ONTAP Select 9.17.1, SnapMirror Cloud è supportato da ONTAP Select. SnapMirror Cloud è una funzionalità ONTAP concessa in licenza, abilitata per impostazione predefinita quando si distribuisce un cluster ONTAP Select 9.17.1 o si aggiorna un cluster ONTAP Select esistente alla versione 9.17.1.
+
--
https://docs.netapp.com/us-en/ontap/concepts/snapmirror-cloud-backups-object-store-concept.html["Scopri di più sui backup cloud SnapMirror su storage di oggetti"^].

--
Supporto per SnapLock Select Enterprise:: A partire da ONTAP Select 9.17.1, le nuove distribuzioni dispongono automaticamente della licenza SnapLock Select Enterprise (incluso il blocco snapshot antimanomissione).  Per gli aggiornamenti da ONTAP Select 9.16.1 e versioni precedenti, è necessario scaricare la licenza SnapLock Select dalink:https://mysupport.netapp.com/site/["Sito di supporto NetApp"^] e applicarlo manualmente.
Supporto per vSAN ESA su cluster multi-nodo:: A partire da ONTAP Select 9.17.1, il supporto per vSAN Express Storage Architecture (ESA) è esteso per distribuire cluster multi-nodo. Questo miglioramento consente di distribuire configurazioni vSAN ESA.
+
--
vSAN ESA è una configurazione specifica di ESX e una nuova architettura per VMware vSAN introdotta in vSphere 8. vSAN ESA è progettato per offrire maggiore efficienza, scalabilità e prestazioni, in particolare quando si utilizzano dispositivi flash TLC basati su NVMe.

ONTAP Select Deploy e ONTAP Select per ESX supportano la configurazione di un cluster ONTAP Select a nodo singolo e multi-nodo, utilizzando un vSAN o un tipo di datastore di array esterno per il suo pool di archiviazione.

[NOTE]
====
Per eseguire operazioni sulla libreria dei contenuti, è necessario accedere a livelli di autorizzazione aggiuntivi. Questa operazione è necessaria per le distribuzioni vSAN ESA se si lavora con ruoli limitati.

link:https://docs.netapp.com/us-en/ontap-select/reference_plan_dep_vmware.html["Scopri come accedere ai livelli di autorizzazione per le operazioni della libreria di contenuti"^].

====
--
Supporto driver NDA aggiornato:: A partire da ONTAP Select 9.17.1, il driver di dispositivo NDA (NVMe Direct Access) di FreeBSD sostituisce il driver NVD (NVMe Express Disk Driver). Il driver di FreeBSD fornisce supporto per i dispositivi ad accesso diretto implementando il protocollo di comando NVMe. Quando si distribuisce un cluster ONTAP Select 9.17.1 o si aggiorna un cluster ONTAP Select esistente alla versione 9.17.1, il driver di FreeBSD viene avviato per impostazione predefinita durante la configurazione dei dispositivi NVMe.
+
--
Per ONTAP Select 9.16.1 e versioni precedenti, NVD continua a fornire supporto per i dispositivi NVMe nella distribuzione ONTAP Select .

--
Supporto aggiornato per l'hypervisor KVM:: A partire da ONTAP Select 9.17.1, l'hypervisor KVM è supportato su Red Hat Enterprise Linux (RHEL) 10.1, 10.0, 9.7, and 9.6 e Rocky Linux 10.1, 10.0, 9.7, and 9.6.


[NOTE]
====
Esistono limitazioni al flusso di lavoro RAID software per gli hypervisor KVM su host RHEL 10.1 e 10.0 e Rocky Linux 10.1 e 10.0. Per ulteriori informazioni, consultare i seguenti articoli della Knowledge Base:

* link:https://kb.netapp.com/on-prem/ontap/ontap-select/Select-Issues/CDEPLOY-4020["CDEPLOY-4020: ONTAP Select Deploy: messaggio di avviso durante la creazione del Cluster HWR utilizzando RHEL 10 e ROCKY 10"^]
* link:https://kb.netapp.com/on-prem/ontap/ontap-select/Select-Issues/CDEPLOY-4025["CDEPLOY-4025: ONTAP Select DeployGUI: pool di archiviazione e dischi di archiviazione non visibili per SWR nella pagina di creazione del cluster su host con RHEL10/Rocky 10"^]


====
Supporto VMware ESXi migliorato:: ONTAP Select 9.17.1 include il supporto per VMware ESXi 9.0.




== ONTAP Select 9.16.1

ONTAP Select 9.16.1 include numerose nuove funzionalità e miglioramenti.

Supporto aggiornato per i file di licenza NetApp:: A partire da ONTAP Select 9.16.1, il supporto per NetApp License File (NLF) è stato aggiornato. Il nuovo formato NLF include le licenze per le funzionalità ARP, ONTAP S3 e S3 SnapMirror . link:reference_lic_ontap_features.html#ontap-features-automatically-enabled-by-default["Saperne di più"].
+
--
Per una nuova distribuzione ONTAP Select 9.16.1, il nuovo formato NLF viene applicato automaticamente. Quando si aggiorna una distribuzione ONTAP Select esistente alla versione 9.16.1, il nuovo formato NLF non viene applicato. Per ottenere le licenze delle funzionalità ARP, ONTAP S3 e S3 SnapMirror , è necessario scaricare l'NLF aggiornato dopo l'aggiornamento. Se si ripristina ONTAP Select 9.15.1 o una versione precedente, è necessario reinstallare le licenze delle funzionalità in uso prima dell'aggiornamento.

--
Supporto per la protezione autonoma dal ransomware:: ONTAP Select 9.16.1 introduce il supporto per la protezione autonoma dal ransomware (ARP). ONTAP Select 9.16.1 supporta solo gli aggiornamenti manuali per ARP, mentre gli aggiornamenti automatici non sono supportati. La licenza per la funzionalità ARP è inclusa nel NLF per ONTAP Select 9.16.1. link:reference_lic_ontap_features.html#ontap-features-automatically-enabled-by-default["Saperne di più"].
Supporto VMware ESXi migliorato:: ONTAP Select 9.16.1 include il supporto per VMware ESXi 8.0 U3.
Supporto aggiornato per l'hypervisor KVM:: A partire da ONTAP Select 9.16.1, l'hypervisor KVM è supportato su RHEL 9.5 e Rocky Linux 9.5.




== ONTAP Select 9.15.1

ONTAP Select 9.15.1 include numerose nuove funzionalità e miglioramenti.

Supporto aggiornato per l'hypervisor KVM:: A partire da ONTAP Select 9.15.1, l'hypervisor Kernel-Based Virtual Machine (KVM) è supportato su RHEL 9.4 e Rocky Linux 9.4.
Supporto per l'espansione e la contrazione dei cluster:: A partire da ONTAP Select 9.15.1, è supportata l'espansione e la contrazione dei cluster.
+
--
* Espansione del cluster da cluster a sei nodi a cluster a otto nodi
+
È possibile aumentare le dimensioni del cluster da sei a otto nodi con la funzionalità di espansione cluster. Le espansioni da uno, due o quattro nodi a sei o otto nodi non sono attualmente supportate. link:task_cluster_expansion_contraction.html#expand-the-cluster["Saperne di più"].

* Contrazione del cluster da otto nodi a sei nodi
+
È possibile ridurre le dimensioni del cluster da otto nodi a sei nodi con la funzionalità di contrazione dei cluster. Le contrazioni dei cluster da sei o otto nodi a uno, due o quattro nodi non sono attualmente supportate. link:task_cluster_expansion_contraction.html#contract-the-cluster["Saperne di più"].



--



NOTE: Il supporto per l'espansione e la contrazione dei cluster è limitato ai soli cluster ESX.



== ONTAP Select 9.14.1

ONTAP Select 9.14.1 include numerose nuove funzionalità e miglioramenti.

Supporto per l'hypervisor KVM:: A partire da ONTAP Select 9.14.1, è stato ripristinato il supporto per l'hypervisor KVM. In precedenza, il supporto per l'implementazione di un nuovo cluster su un hypervisor KVM era stato rimosso in ONTAP Select 9.10.1, mentre il supporto per la gestione di cluster e host KVM esistenti, ad eccezione della disconnessione o dell'eliminazione, era stato rimosso in ONTAP Select 9.11.1.
Il plug-in di distribuzione VMware vCenter non è più supportato:: A partire da ONTAP Select 9.14.1, il plug-in Deploy VMware vCenter non è più supportato.
Supporto ONTAP Select Deploy aggiornato:: Se si utilizza una versione di ONTAP Select Deploy 9.14.1 precedente alla 9.14.1P2, è necessario eseguire l'aggiornamento a ONTAP Select Deploy 9.14.1P2 il prima possibile. Per maggiori informazioni, vedere illink:https://library.netapp.com/ecm/ecm_download_file/ECMLP2886733["Note sulla versione ONTAP Select 9.14.1"^] .
Supporto VMware ESXi migliorato:: ONTAP Select 9.14.1 include il supporto per VMware ESXi 8.0 U2.




== ONTAP Select 9.13.1

ONTAP Select 9.13.1 include numerose nuove funzionalità e miglioramenti.

Supporto per NVMe su TCP:: Quando si esegue l'aggiornamento a ONTAP Select 9.13.1, è necessario disporre della nuova licenza per supportare NVMe su TCP. Questa licenza è inclusa automaticamente quando si distribuisce ONTAP Select per la prima volta dalla versione 9.13.1.
Supporto VMware ESXi aggiornato:: A partire da ONTAP 9.13.1, VMware ESXi 8.0.1 GA (build 20513097) è supportato con la versione hardware 4 e successive.
Supporto ONTAP Select Deploy aggiornato:: A partire da aprile 2024, ONTAP Select Deploy 9.13.1 non è più disponibile sul sito di supporto NetApp . Se si utilizza ONTAP Select Deploy 9.13.1, è necessario eseguire l'aggiornamento a ONTAP Select Deploy 9.14.1P2 il prima possibile. Per maggiori informazioni, vedere illink:https://library.netapp.com/ecm/ecm_download_file/ECMLP2886733["Note sulla versione ONTAP Select 9.14.1"^] .




== ONTAP Select 9.12.1

ONTAP Select 9.12.1 beneficia della maggior parte dei nuovi sviluppi della versione corrente del prodotto principale ONTAP . Non include nuove funzionalità o miglioramenti specifici di ONTAP Select.

A partire da aprile 2024, ONTAP Select Deploy 9.12.1 non è più disponibile sul sito di supporto NetApp . Se si utilizza ONTAP Select Deploy 9.12.1, è necessario eseguire l'aggiornamento a ONTAP Select Deploy 9.14.1P2 il prima possibile. Per maggiori informazioni, vedere illink:https://library.netapp.com/ecm/ecm_download_file/ECMLP2886733["Note sulla versione ONTAP Select 9.14.1"^] .



== ONTAP Select 9.11.1

ONTAP Select 9.11.1 include numerose nuove funzionalità e miglioramenti.

Supporto VMware ESXi migliorato:: ONTAP Select 9.11.1 include il supporto per VMware ESXi 7.0 U3C.
Supporto per VMware NSX-T:: ONTAP Select 9.10.1 e versioni successive sono state qualificate per VMware NSX-T versione 3.1.2. Non si verificano problemi o carenze funzionali quando si utilizza NSX-T con un cluster ONTAP Select a nodo singolo distribuito con un file OVA e l'utility di amministrazione ONTAP Select Deploy. Tuttavia, quando si utilizza NSX-T con un cluster ONTAP Select a più nodi, è necessario tenere presente la seguente limitazione per ONTAP Select 9.11.1:
+
--
* Verificatore di connettività di rete
+
Il controllo della connettività di rete disponibile tramite Deploy CLI non riesce quando viene eseguito su una rete basata su NSX-T.



--
L'hypervisor KVM non è più supportato::
+
--
* A partire da ONTAP Select 9.10.1, non è più possibile distribuire un nuovo cluster sull'hypervisor KVM.
* A partire da ONTAP Select 9.11.1, tutte le funzionalità di gestibilità non sono più disponibili per i cluster e gli host KVM esistenti, ad eccezione delle funzioni di disconnessione ed eliminazione.
+
NetApp consiglia vivamente ai clienti di pianificare ed eseguire una migrazione completa dei dati da ONTAP Select per KVM a qualsiasi altra piattaforma ONTAP , inclusa ONTAP Select per ESXi. Per maggiori informazioni, vedere il https://mysupport.netapp.com/info/communications/ECMLP2877451.html["Avviso EOA"^]



--




== ONTAP Select 9.10.1

ONTAP Select 9.10.1 include numerose nuove funzionalità e miglioramenti.

Supporto per VMware NSX-T:: ONTAP Select 9.10.1 è stato qualificato per VMware NSX-T versione 3.1.2. Non si verificano problemi o carenze funzionali quando si utilizza NSX-T con un cluster ONTAP Select a nodo singolo distribuito con un file OVA e l'utility di amministrazione ONTAP Select Deploy. Tuttavia, quando si utilizza NSX-T con un cluster ONTAP Select a nodo multiplo, è necessario tenere presenti i seguenti requisiti e limitazioni:
+
--
* MTU del cluster
+
È necessario regolare manualmente la dimensione MTU del cluster a 8800 prima di distribuirlo, per tenere conto del sovraccarico aggiuntivo. Le linee guida VMware consigliano di consentire un buffer di 200 byte quando si utilizza NSX-T.

* Configurazione di rete 4x10Gb
+
Per le distribuzioni ONTAP Select su un host VMware ESXi configurato con quattro NIC, l'utilità Deploy richiederà di seguire la best practice di suddividere il traffico interno su due diversi gruppi di porte e il traffico esterno su due diversi gruppi di porte. Tuttavia, quando si utilizza una rete overlay, questa configurazione non funziona e si consiglia di ignorare la raccomandazione. In questo caso, è consigliabile utilizzare solo un gruppo di porte interno e un gruppo di porte esterno.

* Verificatore di connettività di rete
+
Il controllo della connettività di rete disponibile tramite Deploy CLI non riesce quando viene eseguito su una rete basata su NSX-T.



--
L'hypervisor KVM non è più supportato:: A partire da ONTAP Select 9.10.1 non è più possibile distribuire un nuovo cluster sull'hypervisor KVM. Tuttavia, se si aggiorna un cluster da una versione precedente alla versione 9.10.1, è comunque possibile utilizzare l'utilità "Deploy" per amministrare il cluster.




== ONTAP Select 9.9.1

ONTAP Select 9.9.1 include numerose nuove funzionalità e miglioramenti.

Supporto per la famiglia di processori:: A partire da ONTAP Select 9.9.1, ONTAP Select supporta solo i modelli di CPU Intel Xeon Sandy Bridge o successivi.
Supporto VMware ESXi aggiornato:: Il supporto per VMware ESXi è stato migliorato con ONTAP Select 9.9.1. Sono ora supportate le seguenti versioni:
+
--
* ESXi 7.0 U2
* ESXi 7.0 U1


--




== ONTAP Select 9.8

ONTAP Select 9.8 include numerose funzionalità nuove e modificate.

Interfaccia ad alta velocità:: La funzionalità di interfaccia ad alta velocità migliora la connettività di rete offrendo un'opzione sia per 25G (25GbE) che per 40G (40GbE). Per ottenere le migliori prestazioni quando si utilizzano queste velocità più elevate, è necessario seguire le best practice relative alla configurazione della mappatura delle porte, come descritto nella documentazione ONTAP Select .
Supporto VMware ESXi aggiornato:: ONTAP Select 9.8 apporta due modifiche per quanto riguarda il supporto per VMware ESXi.
+
--
* È supportato ESXi 7.0 (build GA 15843807 e successive)
* ESXi 6.0 non è più supportato


--

