---
sidebar: sidebar 
permalink: reference_plan_ots_hardware.html 
keywords: plan, planning, vmware, hardware, hardware requirements 
summary: 'Esistono diversi requisiti hardware e problemi di pianificazione da considerare in relazione all"ambiente VMware.' 
---
= Considerazioni sull'hypervisor VMware e sull'hardware ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Esistono diversi requisiti hardware e problemi di pianificazione da considerare in relazione all'ambiente VMware.



== Requisiti dell'hypervisor

Esistono diversi requisiti relativi all'hypervisor su cui viene eseguito ONTAP Select .


NOTE: Dovresti rivedere illink:reference_release_notes.html["Note sulla versione ONTAP Select"] per eventuali ulteriori restrizioni o limitazioni note.



=== Licenza VMware

Per distribuire un cluster ONTAP Select , la tua organizzazione deve disporre di una licenza VMware vSphere valida per gli host hypervisor su cui è in esecuzione ONTAP Select . È consigliabile utilizzare le licenze appropriate per la tua distribuzione.



=== Compatibilità software

È possibile distribuire ONTAP Select sugli hypervisor KVM ed ESXi.

[role="tabbed-block"]
====
.KVM
--
ONTAP Select supporta le seguenti versioni dell'hypervisor KVM:

* KVM su Red Hat Enterprise Linux 9.6, 9.5, 9.4, 9.2, 9.1, 9.0, 8.8, 8.7 e 8.6
* KVM su Rocky Linux 9.6, 9.5, 9.4, 9.3, 9.2, 9.1, 9.0, 8.9, 8.8, 8.7 e 8.6


--
.ESXi
--
ONTAP Select supporta le seguenti versioni dell'hypervisor ESXi:

* VMware ESXi 9.0
* VMware ESXi 8.0 U3
* VMware ESXi 8.0 U2
* VMware ESXi 8.0 U1 (build 21495797)
* VMware ESXi 8.0 GA (build 20513097)
* VMware ESXi 7.0 GA (build 15843807 o successiva) inclusi 7.0 U3C, U2 e U1



NOTE: NetApp supporta ONTAP Select sulle versioni identificate di ESXi, a condizione che VMware continui a supportare le stesse versioni.


NOTE: ESXi 6.5 GA ed ESXi 6.7 GA hanno raggiunto lo stato di fine disponibilità. Se si dispone di cluster ONTAP Select con queste versioni, è necessario eseguire l'aggiornamento alle versioni supportate come da https://mysupport.netapp.com/matrix["Strumento di matrice di interoperabilità (IMT)"^] .

--
====


=== VMware vCenter e host ESXi autonomi

Se un host hypervisor ESXi è gestito da un server vCenter, è necessario registrarlo nell'utility di amministrazione Deploy utilizzando le credenziali vCenter. Non è possibile registrare l'host come host autonomo utilizzando le credenziali ESXi.



== Requisiti hardware principali

L'host hypervisor fisico su cui si distribuisce ONTAP Select deve soddisfare diversi requisiti hardware. È possibile scegliere qualsiasi piattaforma per l'host hypervisor, purché soddisfi i requisiti hardware minimi. I seguenti fornitori offrono piattaforme hardware supportate: Cisco, Dell, HP, Fujitsu, Lenovo e Supermicro.


NOTE: A partire da ONTAP Select 9.9.1, sono supportati solo i modelli di CPU basati su Intel Xeon Sandy Bridge o versioni successive.

Fare riferimento al https://mysupport.netapp.com/matrix["Strumento matrice di interoperabilità,window=_blank"] per maggiori informazioni.



=== Requisiti hardware di base

Esistono diversi requisiti hardware comuni che si applicano a tutte le piattaforme, indipendentemente dal tipo di istanza del nodo o dall'offerta di licenza.

.Processore
I microprocessori supportati includono i processori Intel Xeon per Server, vederelink:https://www.intel.com/content/www/us/en/products/processors/xeon/view-all.html?Processor+Type=1003["Processori Intel Xeon,window=_blank"] per maggiori informazioni.


NOTE: I processori Advanced Micro Devices (AMD) non sono supportati con ONTAP Select.

.Configurazione Ethernet
Sono supportate diverse configurazioni Ethernet in base alle dimensioni del cluster.

[cols="2,3,3"]
|===
| Dimensione del cluster | Requisiti minimi | Requisiti consigliati 


| Cluster a nodo singolo | 2 x 1 GbE | 2 x 10 GbE 


| Cluster a due nodi o MetroCluster SDS | 4 x 1 GbE o 1 x 10 GbE | 2 x 10 GbE 


| Cluster a quattro, sei o otto nodi | 2 x 10 GbE | 4 x 10 GbE o 2 x 25/40 GbE 
|===


=== Requisiti hardware aggiuntivi in base al tipo di istanza

Sono previsti diversi requisiti hardware aggiuntivi in base al tipo di istanza del nodo.

Fare riferimento alink:concept_lic_platforms.html["Comprendere le offerte di licenza della piattaforma"] per maggiori informazioni.

[cols="a1,a2,a2,a2"]
|===
| Dimensione del nodo | Core della CPU | Memoria | Offerta di licenza della piattaforma richiesta 


| Piccolo | Sei core fisici o più, di cui quattro riservati per ONTAP Select | 24 GB o superiore, con 16 GB riservati per ONTAP Select | Standard, premium o premium XL 


| Medio | Dieci core fisici o più, di cui otto riservati per ONTAP Select | 72 GB o superiore, con 64 GB riservati per ONTAP Select | Premium o premium XL 


| Grande | Diciotto core fisici o più, di cui sedici riservati per ONTAP Select | 136 GB o superiore, con 128 GB riservati per ONTAP Select | Premium XL 
|===

NOTE: Sono previsti requisiti aggiuntivi per lo spazio su disco in base alla licenza della piattaforma. Vederelink:reference_plan_ots_storage.html["Archiviazione e RAID"] per maggiori informazioni.
