---
sidebar: sidebar 
permalink: reference_plan_ots_two_node.html 
keywords: plan, planning, two nodes, two node clusters 
summary: 'L"implementazione di un cluster a due nodi con HA richiede la stessa pianificazione e configurazione utilizzate per altre configurazioni di nodi del cluster. Tuttavia, ci sono diverse differenze di cui è necessario essere consapevoli quando si crea un cluster a due nodi.' 
---
= ONTAP Select cluster a due nodi con HA
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
L'implementazione di un cluster a due nodi con HA richiede la stessa pianificazione e configurazione utilizzate per altre configurazioni di nodi del cluster. Tuttavia, ci sono diverse differenze di cui è necessario essere consapevoli quando si crea un cluster a due nodi.

.Ambiente di destinazione
Il cluster a due nodi è costituito da una coppia HA ed è stato progettato specificamente per distribuzioni in uffici remoti e filiali.


NOTE: Sebbene sia stato progettato principalmente per ambienti di uffici remoti e filiali, è possibile anche distribuire un cluster a due nodi nel data center, se necessario.

.Licenza
È possibile implementare un cluster a due nodi utilizzando qualsiasi licenza VMware vSphere. Tuttavia, le licenze VMware ROBO Standard e Advanced sono ideali per le implementazioni in sedi remote e filiali.

.Servizio di mediazione
Quando un cluster è composto da due nodi, non è possibile raggiungere il quorum richiesto in caso di guasto o perdita di comunicazione di un nodo. Per risolvere questo tipo di situazioni di "split brain", ogni istanza dell'utility ONTAP Select Deploy include un servizio mediatore. Questo servizio si connette a ciascun nodo nei cluster attivi a due nodi per monitorare le coppie HA e supportare la gestione dei guasti. Il servizio mediatore mantiene le informazioni sullo stato HA su una destinazione iSCSI dedicata associata a ciascun cluster a due nodi.


CAUTION: Se si dispone di uno o più cluster a due nodi attivi, la macchina virtuale ONTAP Select Deploy che amministra i cluster deve essere sempre in esecuzione. Se la macchina virtuale ONTAP Select Deploy viene arrestata o non funziona correttamente, il servizio mediatore non è disponibile e la funzionalità HA viene persa per i cluster a due nodi.

.Ubicazione del cluster e del servizio mediatore
Poiché i cluster a due nodi vengono in genere distribuiti in una filiale o in un ufficio remoto, possono essere distanti dal data center aziendale e dall'utilità ONTAP Select Deploy che fornisce supporto amministrativo. Con questa configurazione, il traffico di gestione tra l'utilità ONTAP Select Deploy e il cluster scorre sulla WAN. Consultare le note di rilascio per ulteriori informazioni su limitazioni e restrizioni.

.Eseguire il backup dei dati di configurazione di Deploy
È una buona praticalink:task_cli_clusters.html["eseguire il backup dei dati di configurazione ONTAP Select Deploy"] regolarmente, anche dopo aver creato un cluster. Questo diventa particolarmente importante con i cluster a due nodi, a causa dei dati di configurazione del mediatore inclusi nel backup.

.Indirizzo IP statico assegnato a Deploy
È necessario assegnare un indirizzo IP statico all'utilità di amministrazione ONTAP Select Deploy. Questo requisito si applica a tutte le istanze ONTAP Select Deploy che gestiscono uno o più cluster a due nodi ONTAP Select .
