---
sidebar: sidebar 
permalink: reference_plan_ots_general.html 
keywords: plan, planning, general requirements 
summary: 'Esistono diversi requisiti generali che dovresti prendere in considerazione quando pianifichi un"implementazione ONTAP Select .' 
---
= Requisiti ONTAP Select e considerazioni sulla pianificazione
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Ci sono diversi requisiti generali da considerare quando si pianifica un'implementazione ONTAP Select .



== Conoscenze e competenze Linux richieste per KVM

Linux con l'hypervisor KVM è un ambiente complesso in cui lavorare. Prima di distribuire ONTAP Select su KVM, è necessario disporre delle conoscenze e delle competenze necessarie.

Distribuzione del server Linux:: È richiesta esperienza con la specifica distribuzione Linux da utilizzare per la distribuzione ONTAP Select . In particolare, è necessario essere in grado di svolgere le seguenti attività:
+
--
* Installa la distribuzione Linux
* Configurare il sistema tramite la CLI
* Aggiungere pacchetti software e tutte le dipendenze


--


Per ulteriori informazioni sulla preparazione del server Linux, inclusi i pacchetti software e la configurazione richiesti, consultare la checklist di configurazione dell'host. Fare riferimento ai requisiti dell'hypervisor per le distribuzioni Linux attualmente supportate.

Distribuzione e amministrazione KVM:: È necessario avere familiarità con i concetti generali di virtualizzazione. Inoltre, esistono diversi comandi della CLI Linux che è necessario utilizzare durante l'installazione e la gestione ONTAP Select in un ambiente KVM:
+
--
* `virt-install`
* `virsh`
* `lsblk`
* `lvs`
* `vgs`
* `pvs`


--
Configurazione di rete e Open vSwitch:: È necessario avere familiarità con i concetti di networking e con la configurazione degli switch di rete. Inoltre, è richiesta esperienza con Open vSwitch. È necessario utilizzare i seguenti comandi di rete come parte della configurazione della rete ONTAP Select in un ambiente KVM:
+
--
* `ovs-vsctl`
* `ip`
* `ip link`
* `systemctl`


--




== Dimensioni del cluster e considerazioni correlate

Ci sono diverse questioni di pianificazione relative alle dimensioni del cluster che dovresti prendere in considerazione.

Numero di nodi nel cluster:: Un cluster ONTAP Select è composto da uno, due, quattro, sei o otto nodi. È necessario determinare la dimensione del cluster in base ai requisiti dell'applicazione. Ad esempio, se è necessaria la funzionalità HA per un'implementazione aziendale, è consigliabile utilizzare un cluster multi-nodo.
Dedicato contro collocato:: In base al tipo di applicazione, è necessario determinare se la distribuzione segue il modello dedicato o collocato. Si noti che il modello collocato può essere più complesso a causa della diversità dei carichi di lavoro e della maggiore integrazione.




== Considerazioni sull'host dell'hypervisor

Ci sono diverse questioni di pianificazione relative all'host dell'hypervisor che dovresti prendere in considerazione.


CAUTION: Non modificare direttamente la configurazione di una macchina virtuale ONTAP Select, a meno che non venga richiesto dal supporto NetApp . Una macchina virtuale deve essere configurata e modificata solo tramite l'utility di amministrazione Deploy. Apportare modifiche a una macchina virtuale ONTAP Select al di fuori dell'utility Deploy senza l'assistenza del supporto NetApp può causare il malfunzionamento della macchina virtuale e renderla inutilizzabile.

Indipendente dall'hypervisor:: Sia ONTAP Select che l'utilità di amministrazione ONTAP Select Deploy sono indipendenti dall'hypervisor. Entrambi supportano i seguenti hypervisor.
+
--
* VMware ESXi
* Macchina virtuale basata sul kernel (KVM)


--



NOTE: A partire da ONTAP Select 9.14.1, è stato ripristinato il supporto per l'hypervisor KVM. In precedenza, il supporto per l'implementazione di un nuovo cluster su un hypervisor KVM era stato rimosso in ONTAP Select 9.10.1, mentre il supporto per la gestione di cluster e host KVM esistenti, ad eccezione della disconnessione o dell'eliminazione, era stato rimosso in ONTAP Select 9.11.1.

Per ulteriori dettagli sulle piattaforme supportate, fare riferimento alle informazioni di pianificazione e alle note di rilascio specifiche dell'hypervisor.

Hypervisor per ONTAP Select nodi e utilità di amministrazione:: Sia l'utility di amministrazione Deploy che i nodi ONTAP Select vengono eseguiti come macchine virtuali. L'hypervisor scelto per l'utility Deploy è indipendente da quello scelto per i nodi ONTAP Select . L'abbinamento dei due è estremamente flessibile:
+
--
* L'utilità di distribuzione in esecuzione su VMware ESXi può creare e gestire cluster ONTAP Select su VMware ESXi o KVM
* L'utilità di distribuzione in esecuzione su KVM può creare e gestire cluster ONTAP Select su VMware ESXi o KVM


--
Una o più istanze del nodo ONTAP Select per host:: Ogni nodo ONTAP Select viene eseguito come una macchina virtuale dedicata. È possibile creare più nodi sullo stesso host hypervisor, con le seguenti restrizioni:
+
--
* Non è possibile eseguire più nodi di un singolo cluster ONTAP Select sullo stesso host. Tutti i nodi di uno specifico host devono appartenere a cluster ONTAP Select diversi.
* È necessario utilizzare un archivio esterno.
* Se si utilizza il RAID software, è possibile distribuire un solo nodo ONTAP Select sull'host.


--
Coerenza dell'hypervisor per i nodi all'interno di un cluster:: Tutti gli host all'interno di un cluster ONTAP Select devono utilizzare la stessa versione e release del software hypervisor.
Numero di porte fisiche su ciascun host:: È necessario configurare ogni host in modo che utilizzi una, due o quattro porte fisiche. Sebbene sia possibile configurare le porte di rete in modo flessibile, è consigliabile seguire queste raccomandazioni ove possibile:
+
--
* Un host in un cluster a nodo singolo dovrebbe avere due porte fisiche.
* Ogni host in un cluster multi-nodo dovrebbe avere quattro porte fisiche


--
Integrazione di ONTAP Select con un cluster basato su hardware ONTAP:: Non è possibile aggiungere un nodo ONTAP Select direttamente a un cluster ONTAP basato su hardware. Tuttavia, è possibile stabilire facoltativamente una relazione di peering tra un cluster ONTAP Select e un cluster ONTAP basato su hardware.




== Considerazioni sullo stoccaggio

Esistono diverse problematiche di pianificazione relative all'archiviazione host che dovresti prendere in considerazione.

Tipo RAID:: Quando si utilizza un DAS (Direct-Attached Storage) su ESXi, è necessario decidere se utilizzare un controller RAID hardware locale o la funzionalità RAID software inclusa in ONTAP Select. Se si utilizza il software RAID, vederelink:reference_plan_ots_storage.html["Considerazioni su archiviazione e RAID"] per maggiori informazioni.
Archiviazione locale:: Quando si utilizza un archivio locale gestito da un controller RAID, è necessario decidere quanto segue:
+
--
* Se utilizzare uno o più gruppi RAID
* Se utilizzare uno o più LUN


--
Archiviazione esterna:: Quando si utilizza la soluzione ONTAP Select vNAS, è necessario decidere dove si trovano i datastore remoti e come accedervi. ONTAP Select vNAS supporta le seguenti configurazioni:
+
--
* VMware vSAN
* Array di archiviazione esterno generico


--
Stima dello spazio di archiviazione necessario:: È necessario determinare la quantità di spazio di archiviazione necessaria per i nodi ONTAP Select . Questa informazione è necessaria per l'acquisizione delle licenze acquistate con capacità di archiviazione. Per ulteriori informazioni, consultare la sezione Limitazioni sulla capacità di archiviazione.



NOTE: La capacità di archiviazione ONTAP Select corrisponde alla dimensione totale consentita dei dischi dati collegati alla macchina virtuale ONTAP Select .

Modello di licenza per la distribuzione in produzione:: È necessario selezionare il modello di licenza Capacity Tiers o Capacity Pools per ogni cluster ONTAP Select distribuito in un ambiente di produzione. Consultare la sezione _Licenza_ per ulteriori informazioni.




== Autenticazione tramite l'archivio delle credenziali

L'archivio credenziali ONTAP Select Deploy è un database contenente informazioni sugli account. Deploy utilizza le credenziali dell'account per eseguire l'autenticazione dell'host nell'ambito della creazione e gestione del cluster. È importante conoscere come l'archivio credenziali viene utilizzato durante la pianificazione di un'implementazione di ONTAP Select .


NOTE: Le informazioni dell'account vengono archiviate in modo sicuro nel database mediante l'algoritmo di crittografia Advanced Encryption Standard (AES) e l'algoritmo di hashing SHA-256.

Tipi di credenziali:: Sono supportati i seguenti tipi di credenziali:
+
--
* ospite
+
La credenziale *host* viene utilizzata per autenticare un host hypervisor come parte della distribuzione di un nodo ONTAP Select direttamente su ESXi o KVM.

* centro verticale
+
La credenziale *vcenter* viene utilizzata per autenticare un server vCenter come parte della distribuzione di un nodo ONTAP Select su ESXi quando l'host è gestito da VMware vCenter.



--
Accesso:: L'accesso all'archivio credenziali avviene internamente durante l'esecuzione delle normali attività amministrative di Deploy, come l'aggiunta di un host hypervisor. È anche possibile gestire l'archivio credenziali direttamente tramite l'interfaccia utente web e la CLI di Deploy.


.Informazioni correlate
* link:reference_plan_ots_storage.html["Considerazioni su archiviazione e RAID"]

