---
sidebar: sidebar 
permalink: reference_plan_ots_robo.html 
keywords: plan, planning, remote and branch office, robo 
summary: 'È possibile implementare ONTAP Select in un ambiente di ufficio/filiale remoto (ROBO). Durante la pianificazione dell"implementazione ROBO, è necessario selezionare la configurazione che supporti i propri obiettivi.' 
---
= ONTAP Select distribuzioni di uffici remoti e filiali
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile implementare ONTAP Select in un ambiente di ufficio/filiale remoto (ROBO). Durante la pianificazione dell'implementazione ROBO, è necessario selezionare la configurazione che supporti i propri obiettivi.

Sono disponibili due configurazioni principali quando si distribuisce ONTAP Select in un ambiente ROBO.


NOTE: È possibile utilizzare qualsiasi licenza VMware vSphere durante la distribuzione ONTAP Select.

.ONTAP Select cluster a due nodi con ONTAP HA
Il cluster a due nodi ONTAP Select è costituito da una coppia HA ed è ideale per le distribuzioni ROBO.

.ONTAP Select a nodo singolo con supporto VMware
È possibile implementare un cluster a nodo singolo ONTAP Select in un ambiente ROBO. Sebbene un singolo nodo non disponga di funzionalità HA native, è possibile implementare il cluster in uno dei seguenti modi per garantire la protezione dello storage:

* Archiviazione esterna condivisa tramite VMware HA
* VMware vSAN



NOTE: Se si utilizza vSAN, è necessario disporre di una licenza VMware vSAN ROBO.
