---
sidebar: sidebar 
permalink: task_cli_migrate_deploy.html 
keywords: administer, administering, cli, deploy, deploy instance, migrate 
summary: 'È possibile migrare un"istanza esistente dell"utilità di amministrazione Deploy su una nuova macchina virtuale utilizzando l"interfaccia della riga di comando.' 
---
= Migrare un'istanza ONTAP Select Deploy su una nuova macchina virtuale
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile migrare un'istanza esistente dell'utilità di amministrazione Deploy su una nuova macchina virtuale utilizzando l'interfaccia della riga di comando.

Questa procedura si basa sulla creazione di una nuova macchina virtuale che utilizza i dati di configurazione della macchina virtuale originale. La nuova macchina virtuale e quella originale devono eseguire la stessa versione e release dell'utilità Deploy. Non è possibile migrare a una versione e release diversa dell'utilità Deploy.



== Passaggio 1: eseguire il backup dei dati di configurazione di distribuzione

È necessario creare un backup dei dati di configurazione di Deploy durante la migrazione della macchina virtuale. È inoltre necessario creare un backup dopo aver distribuito un cluster ONTAP Select . I dati vengono salvati in un singolo file crittografato che è possibile scaricare sulla workstation locale.

.Prima di iniziare
* Assicurarsi che Deploy non stia eseguendo altre attività durante l'operazione di backup.
* Salvare l'immagine originale della macchina virtuale Deploy.
+

CAUTION: L'immagine originale della macchina virtuale Deploy sarà necessaria più avanti in questa procedura quando si ripristinano i dati di configurazione Deploy dalla macchina virtuale originale alla nuova.



.Informazioni su questo compito
Il file di backup creato cattura tutti i dati di configurazione della macchina virtuale. Questi dati descrivono aspetti dell'ambiente di distribuzione, inclusi i cluster ONTAP Select .

.Passi
. Sign in all'utility Deploy CLI tramite SSH con l'account amministratore.
. Creare un backup dei dati di configurazione di Deploy, archiviati in una directory interna sul server Deploy:
+
[source, cli]
----
deploy backup create
----
. Quando richiesto, fornire una password per il backup.
+
Il file di backup viene crittografato in base alla password.

. Visualizza i backup disponibili nel sistema:
+
[source, cli]
----
deploy backup show -detailed
----
. Seleziona il file di backup in base alla data nel campo *Creato* e registra il valore *URL di download*.
+
È possibile accedere al file di backup tramite l'URL.

. Utilizzando un browser Web o un'utilità come Curl, scarica il file di backup sulla tua workstation locale con l'URL.




== Passaggio 2: installare una nuova istanza della macchina virtuale Deploy

È necessario creare una nuova istanza della macchina virtuale Deploy che è possibile aggiornare con i dati di configurazione della macchina virtuale originale.

.Prima di iniziare
È necessario avere familiarità con le procedure utilizzate per scaricare e distribuire la macchina virtuale ONTAP Select Deploy in un ambiente VMware.

.Informazioni su questo compito
Questo compito è descritto ad alto livello.

.Passi
. Crea una nuova istanza della macchina virtuale Deploy:
+
.. Scarica l'immagine della macchina virtuale.
.. Distribuire la macchina virtuale e configurare l'interfaccia di rete.
.. Accedere all'utilità Deploy tramite SSH.




.Informazioni correlate
link:task_install_deploy.html["Installa ONTAP Select Distribuisci"]



== Passaggio 3: ripristinare i dati di configurazione di distribuzione nella nuova macchina virtuale

È necessario ripristinare i dati di configurazione dalla macchina virtuale originale dell'utilità Deploy alla nuova macchina virtuale. I dati sono contenuti in un unico file che è necessario caricare dalla workstation locale.

.Prima di iniziare
È necessario disporre dei dati di configurazione di un backup precedente. I dati sono contenuti in un unico file e devono essere disponibili sulla workstation locale.

.Passi
. In una shell dei comandi sulla workstation locale, utilizzare l'utilità sftp per caricare il file di backup sulla macchina virtuale Deploy, come mostrato nell'esempio seguente:
+
....
sftp admin@10.234.81.101 (provide password when prompted)
put deploy_backup_20190601162151.tar.gz
exit
....
. Sign in all'utility Deploy CLI tramite SSH con l'account amministratore.
. Ripristinare i dati di configurazione:
+
[source, cli]
----
deploy backup restore -path <path_name> -filename <file_name>
----
+
Comando di esempio

+
`deploy backup restore -path /home/admin -filename deploy_backup_20180601162151.tar.gz`


