---
sidebar: sidebar 
permalink: task_cli_deploy_image_add.html 
keywords: administer, administering, cli, deploy, ontap select image, add 
summary: 'Aggiungi un"immagine ONTAP Select alla tua istanza dell"utilità di amministrazione Deploy. Dopo l"installazione, puoi utilizzarla quando distribuisci un cluster ONTAP Select.' 
---
= Aggiungi un'immagine ONTAP Select da distribuire
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Aggiungi un'immagine ONTAP Select alla tua istanza dell'utilità di amministrazione Deploy. Dopo che l'immagine è stata installata, puoi utilizzarla quando distribuisci un cluster ONTAP Select.

.Prima di iniziare
Prima di aggiungere nuove immagini ONTAP Select da distribuire, è necessario rimuovere tutte le immagini non necessarie.


NOTE: Si consiglia di aggiungere un'immagine ONTAP Select solo con una versione precedente a quella originale inclusa nell'istanza dell'utility Deploy. L'aggiunta di versioni successive di ONTAP Select, non appena disponibili da NetApp , non è una configurazione supportata.



== Passaggio 1: scarica l'immagine di installazione

Per iniziare il processo di aggiunta di un'immagine ONTAP Select a un'istanza dell'utility Deploy, è necessario scaricare l'immagine di installazione dal sito di supporto NetApp . L'immagine di installazione ONTAP Select è formattata come un singolo file compresso.

.Passi
. Accedi alla link:https://mysupport.netapp.com/site/downloads/["Download dal sito di supporto NetApp"^] page.
. Scorri verso il basso e seleziona *ONTAP Select Image*.
. Seleziona la versione desiderata dell'immagine di installazione.
. Rivedi il Contratto di licenza con l'utente finale (EULA) e seleziona *Accetta e continua*.
. Seleziona e scarica il pacchetto *ONTAP Select Image Install* appropriato. Rispondi a tutte le richieste secondo necessità.




== Passaggio 2: carica l'immagine di installazione su Deploy

Dopo aver acquisito l'immagine di installazione ONTAP Select , è necessario caricare il file sulla macchina virtuale Deploy.

.Prima di iniziare
Verifica di avere il file immagine di installazione disponibile sulla tua workstation locale. Devi anche disporre della password per l'account utente amministratore di Deploy.

.Informazioni su questo compito
Questa attività descrive un metodo per caricare il file sulla macchina virtuale Deploy. Potrebbero esserci altre opzioni più adatte al tuo ambiente.

.Fare un passo
. In una shell dei comandi sulla workstation locale, carica il file immagine sulla macchina virtuale Deploy, come mostrato negli esempi seguenti:
+
....
scp image_v_93_install_esx.tgz admin@10.234.81.101:/home/admin (provide password when prompted)
....
+
....
sftp admin@10.234.81.101 (provide password when prompted)
put image_v_93_install_esx.tgz
exit
....


.Risultato
Il file di installazione del nodo è archiviato nella directory home dell'utente amministratore.



== Passaggio 3: aggiungere l'immagine di installazione

Aggiungere l'immagine di installazione ONTAP Select alla directory Deploy images in modo che sia disponibile quando si distribuisce un nuovo cluster.

.Prima di iniziare
È necessario sapere in quale directory è stato inserito il file immagine di installazione nella macchina virtuale dell'utilità Deploy. Si presume che il file si trovi nella directory home dell'amministratore.

.Passi
. Sign in all'utility Deploy CLI tramite SSH con l'account amministratore (admin).
. Avviare la shell Bash:
+
[source, cli]
----
shell bash
----
. Inserire il file immagine di installazione nella directory images, come mostrato nell'esempio seguente:
+
`tar -xf image_v_93_install_esx.tgz -C /opt/netapp/images/`





== Passaggio 4: visualizzare le immagini di installazione disponibili

Visualizza le immagini ONTAP Select disponibili durante la distribuzione di un nuovo cluster.

.Passi
. Accedere alla pagina web della documentazione online nella macchina virtuale dell'utilità Deploy e accedere utilizzando l'account amministratore (admin):
+
`\http://<FQDN|IP_ADDRESS>/api/ui`

+
Utilizzare il nome di dominio o l'indirizzo IP della macchina virtuale di distribuzione.

. Vai in fondo alla pagina e seleziona *Distribuisci*, quindi seleziona *OTTIENI /immagini*.
. Selezionare *Provalo!* per visualizzare le immagini ONTAP Select disponibili.
. Verificare che l'immagine desiderata sia disponibile.

