---
sidebar: sidebar 
permalink: task_cli_connectivity.html 
keywords: administer, administering, cli, connectivity, network connectivity, network checker 
summary: 'È possibile testare la connettività di rete tra due o più nodi ONTAP Select sulla rete interna del cluster. In genere, questo test viene eseguito prima dell"implementazione di un cluster multi-nodo per rilevare eventuali problemi che potrebbero causare il fallimento dell"operazione.' 
---
= Confermare la connettività di rete tra i nodi ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile testare la connettività di rete tra due o più nodi ONTAP Select sulla rete interna del cluster. In genere, questo test viene eseguito prima dell'implementazione di un cluster multi-nodo per rilevare eventuali problemi che potrebbero causare il fallimento dell'operazione.

.Prima di iniziare
Tutti i nodi ONTAP Select inclusi nel test devono essere configurati e accesi.

.Informazioni su questo compito
Ogni volta che si avvia un test, viene creata in background una nuova esecuzione del processo a cui viene assegnato un identificativo di esecuzione univoco. Può essere attiva una sola esecuzione alla volta.

Il test ha due modalità che ne controllano il funzionamento:

* Rapido: questa modalità esegue un test di base non distruttivo. Viene eseguito un test PING, insieme a un test della dimensione MTU della rete e del vSwitch.
* Estesa: questa modalità esegue un test più completo su tutti i percorsi di rete ridondanti. Se eseguita su un cluster ONTAP Select attivo, le prestazioni del cluster potrebbero risentirne.



NOTE: Si consiglia di eseguire sempre un test rapido prima di creare un cluster multi-nodo. Una volta completato con successo il test rapido, è possibile eseguire un test esteso in base alle proprie esigenze di produzione.

.Passi
. Sign in all'interfaccia della riga di comando dell'utilità Deploy utilizzando l'account amministratore.
. Visualizza le esecuzioni correnti del controllo della connettività di rete e verifica che non ci siano esecuzioni attive:
+
`network connectivity-check show`

. Avviare il controllo della connettività di rete e annotare l'identificatore di esecuzione nell'output del comando:
+
`network connectivity-check start -host-names HOSTNAMES -vswitch-type VSWITCH_TYPE-mode MODE`

+
Esempio

+
[listing]
----
network connectivity-check start -host-names 10.234.81.14
10.234.81.15 -vswitch-type StandardVSwitch -mode quick
----
. Monitorare l'avanzamento del controllo della connettività di rete in base all'identificatore di esecuzione:
+
`network connectivity-check show -run-id RUN_ID`



.Dopo aver finito
Il controllo della connettività di rete normalmente esegue la pulizia rimuovendo tutte le porte temporanee e gli indirizzi IP aggiunti al gruppo di porte ONTAP-Interno. Tuttavia, se il verificatore di connettività non riesce a rimuovere le porte temporanee, è necessario eseguire un'operazione di pulizia manuale rieseguendo il comando CLI con l'opzione `-mode cleanup` . Se non si rimuovono le porte temporanee dal gruppo di porte ONTAP-Interne, la macchina virtuale ONTAP Select potrebbe non essere creata correttamente
