---
sidebar: sidebar 
permalink: task_cli_clusters.html 
keywords: administer, administering, cli, clusters 
summary: Per amministrare un cluster ONTAP Select è possibile eseguire diverse attività correlate. 
---
= Gestire i cluster ONTAP Select utilizzando la CLI
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Esistono diverse attività correlate che è possibile eseguire per amministrare un cluster ONTAP Select utilizzando la CLI.



== Eseguire il backup dei dati di configurazione ONTAP Select Deploy

Backup dei dati di configurazione ONTAP Select Deploy, ad esempio dopo la distribuzione di un cluster. I dati vengono salvati in un singolo file crittografato che è possibile scaricare sulla workstation locale.

Il file di backup creato cattura tutti i dati di configurazione. Questi dati descrivono aspetti dell'ambiente di distribuzione, inclusi i cluster ONTAP Select .

.Prima di iniziare
Assicurarsi che Deploy non stia eseguendo altre attività durante l'operazione di backup.

.Passi
. Sign in all'utility CLI ONTAP Select Deploy tramite SSH con l'account amministratore.
. Creare un backup dei dati di configurazione ONTAP Select Deploy, archiviati in una directory interna sul server ONTAP Select Deploy:
+
[source, cli]
----
deploy backup create
----
. Quando richiesto, fornire una password per il backup.
+
Il file di backup viene crittografato in base alla password.

. Visualizza i backup disponibili nel sistema:
+
[source, cli]
----
deploy backup show -detailed
----
. Seleziona il file di backup in base alla data nel campo *Creato* e registra il valore *URL di download*.
+
È possibile accedere al file di backup tramite l'URL.

. Utilizzando un browser Web o un'utilità come Curl, scarica il file di backup sulla tua workstation locale con l'URL.




== Elimina un cluster ONTAP Select

È possibile eliminare un cluster ONTAP Select quando non è più necessario.

.Prima di iniziare
Il cluster deve essere offline.

.Passi
. Sign in alla CLI della macchina virtuale Distribuisci utilizzando l'account amministratore.
. Visualizza lo stato del cluster:
+
[source, cli]
----
cluster show -name <cluster_name>
----
. Se il cluster non è offline, spostalo in uno stato offline:
+
[source, cli]
----
cluster offline -name <cluster_name>
----
. Dopo aver confermato che il cluster è offline, eliminalo:
+
[source, cli]
----
cluster delete -name <cluster_name>
----

